### ISSUE TITLE
server运行报错

### ISSUE THREAD

**Issue by armysheng** [leng-yue/Lengyue-Vcode#5]
你好，运行服务的时候server会报错，看了下好像Encrypt_Key为空，tdc.js找不到16位的密钥了，导致js报空指针，请问要怎么拿到新的Encrypt_Key，感谢.
```
[2018-04-05 22:50:31,574] ERROR in app: Exception on /parse [POST]
Traceback (most recent call last):
  File "/Users/armysheng/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/armysheng/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/armysheng/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/armysheng/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/armysheng/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/armysheng/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/armysheng/rqking/Lengyue-Vcode/腾讯云滑动/server/run.py", line 114, in get
    enced = JS.call("encrypt", Wait_Encrypt, Encrypt_Key)
  File "/Users/armysheng/venv/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "/Users/armysheng/venv/lib/python3.6/site-packages/execjs/_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "/Users/armysheng/venv/lib/python3.6/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "/Users/armysheng/venv/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/Users/armysheng/venv/lib/python3.6/site-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "/Users/armysheng/venv/lib/python3.6/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: TypeError: Cannot read property 'slice' of null
```

**Comment by 1462326016** [comment]
同样遇到相同错误，找不到加密秘钥了

**Comment by leng-yue** [comment]
腾讯已经更新 请等待代码更新
